language: cpp
compiler: gcc

before_install:
    # add repo so we can use qt5
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa

    # add repo for gcc-4.7
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

    # install CMake from source b/c we need a newer one that has support for Qt 5
    - wget http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz
    - tar -xvzf cmake-3.0.2.tar.gz
    - cd cmake-3.0.2
    - ./bootstrap >> bootstrap.log 2>&1
    - make >> make.log 2>&1
    - sudo make install >> install.log 2>&1
    - cd ..

    - sudo apt-get update -qq
    - sudo apt-get install qt5-default gcc-4.7 g++-4.7

    # use new compilers
    - export CC=gcc-4.7
    - export CXX=g++-4.7

script: make

notifications:
    email: false
